#!/usr/bin/env bash
#
# Regression guard: assert schema/pokkum.schema.json is byte-for-byte what
# `go run ./scripts/gen-schema` produces from internal/ports/config.go right
# now.
#
# Why this exists: schema/pokkum.schema.json is generated by reflection over
# ports.ProjectConfig/ports.BuildProfile (see scripts/gen-schema's doc
# comment) specifically so it cannot drift from the real .pokkum.yaml shape
# the way a hand-written schema would. A generated file that can be quietly
# hand-edited around recreates exactly that drift, just one layer removed:
# the checked-in schema would look authoritative while silently disagreeing
# with the Go types it claims to describe. This guard makes that impossible
# to do silently — same pattern as scripts/check-docs-freshness.sh (which
# this script is modeled on almost line-for-line) and
# scripts/check-build-flags.sh, just checking "regeneration is a no-op" for
# the JSON Schema instead of the roadmap docs or a compiler flag.
#
# Approach: regenerate in place, then ask git whether anything changed. This
# intentionally mutates schema/ as a side effect (like `go generate` +
# `git diff --exit-code`, a common Go idiom) — safe by construction, since a
# clean tree's regenerated output is expected to be identical to what's
# already checked in. A hand-edit to the generated schema, or a
# internal/ports/config.go change nobody regenerated from, shows up here as
# a non-empty diff.
#
# `git status --porcelain` (not `git diff --exit-code`) is used so a
# newly-created or deleted schema file (e.g. the file was deleted by hand)
# is also caught, not just a content change to an existing one.
#
# Usage: bash scripts/check-schema-freshness.sh   # exit 0 clean, 1 on drift

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 1

WATCHED_PATHS=(schema/pokkum.schema.json)

echo "== pokkum.schema.json freshness guard =="
echo "Regenerating from internal/ports/config.go (go run ./scripts/gen-schema)..."

if ! go run ./scripts/gen-schema; then
  echo "FAIL: gen-schema itself failed (a generation bug, or an unsupported field kind was added to" >&2
  echo "      internal/ports/config.go — see schemaForType's doc comment in scripts/gen-schema/reflectwalk.go)." >&2
  echo "      Run 'go run ./scripts/gen-schema' directly to see the full error." >&2
  exit 1
fi

diff_output="$(git status --porcelain -- "${WATCHED_PATHS[@]}")"

if [ -z "$diff_output" ]; then
  echo "PASS: schema/pokkum.schema.json exactly matches internal/ports/config.go."
  exit 0
else
  echo "FAIL: regenerating schema/pokkum.schema.json from internal/ports/config.go produced a diff --" >&2
  echo "      the generated file was hand-edited, or internal/ports/config.go changed without" >&2
  echo "      regenerating. Run 'make schema' and commit the result." >&2
  echo "" >&2
  echo "$diff_output" >&2
  echo "" >&2
  git --no-pager diff -- "${WATCHED_PATHS[@]}" >&2
  exit 1
fi
